# Generated by Django 6.0.3 on 2026-04-11 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_currency', models.CharField(max_length=3, verbose_name='من عملة')),
                ('to_currency', models.CharField(max_length=3, verbose_name='إلى عملة')),
                ('rate', models.DecimalField(decimal_places=6, max_digits=12, verbose_name='سعر الصرف')),
                ('valid_from', models.DateField(verbose_name='صالح من')),
                ('valid_to', models.DateField(blank=True, null=True, verbose_name='صالح حتى')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعّال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'سعر الصرف',
                'verbose_name_plural': 'أسعار الصرف',
                'ordering': ['-valid_from'],
                'indexes': [models.Index(fields=['from_currency', 'to_currency', 'is_active'], name='pricing_exc_from_cu_322569_idx')],
            },
        ),
    ]
