# Generated by Django 6.0.3 on 2026-04-09 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='address',
            field=models.TextField(blank=True, default='', verbose_name='العنوان'),
        ),
    ]
