# Generated by Django 6.0.3 on 2026-04-10 11:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_alter_hotel_address'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='amenities',
            field=models.JSONField(blank=True, default=list, verbose_name='المرافق والخدمات'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='check_in_time',
            field=models.TimeField(blank=True, null=True, verbose_name='وقت الدخول'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='check_out_time',
            field=models.TimeField(blank=True, null=True, verbose_name='وقت المغادرة'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotel',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='بريد الفندق'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='نشط'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='خط العرض'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='خط الطول'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='هاتف الفندق'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='provider_type',
            field=models.CharField(choices=[('direct', 'عقد مباشر'), ('agoda', 'Agoda'), ('booking', 'Booking.com'), ('expedia', 'Expedia'), ('custom', 'مزود مخصص')], default='direct', max_length=20, verbose_name='نوع المزود'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='website',
            field=models.URLField(blank=True, verbose_name='الموقع الإلكتروني'),
        ),
        migrations.AddIndex(
            model_name='hotel',
            index=models.Index(fields=['city', 'stars', 'is_active'], name='hotels_hote_city_id_976f57_idx'),
        ),
        migrations.AddIndex(
            model_name='hotel',
            index=models.Index(fields=['provider_type'], name='hotels_hote_provide_a873bd_idx'),
        ),
    ]
