# Generated by Django 6.0.3 on 2026-04-10 11:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='breakfast_included',
        ),
        migrations.RemoveField(
            model_name='service',
            name='category_data',
        ),
        migrations.RemoveField(
            model_name='service',
            name='is_transfer',
        ),
        migrations.AddField(
            model_name='service',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='dropoff_location',
            field=models.CharField(blank=True, max_length=200, verbose_name='نقطة الوصول'),
        ),
        migrations.AddField(
            model_name='service',
            name='duration_hours',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='المدة بالساعات'),
        ),
        migrations.AddField(
            model_name='service',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict, help_text='للحقول غير المغطاة بالـ schema الثابت', verbose_name='بيانات إضافية'),
        ),
        migrations.AddField(
            model_name='service',
            name='includes_guide',
            field=models.BooleanField(default=False, verbose_name='يشمل مرشد سياحي'),
        ),
        migrations.AddField(
            model_name='service',
            name='includes_meals',
            field=models.BooleanField(default=False, verbose_name='يشمل وجبات'),
        ),
        migrations.AddField(
            model_name='service',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='نشطة'),
        ),
        migrations.AddField(
            model_name='service',
            name='meeting_point',
            field=models.CharField(blank=True, max_length=200, verbose_name='نقطة التجمع'),
        ),
        migrations.AddField(
            model_name='service',
            name='pickup_location',
            field=models.CharField(blank=True, max_length=200, verbose_name='نقطة الانطلاق'),
        ),
        migrations.AddField(
            model_name='service',
            name='price_per',
            field=models.CharField(choices=[('person', 'لكل شخص'), ('group', 'للمجموعة'), ('unit', 'للوحدة')], default='person', max_length=20, verbose_name='السعر لكل'),
        ),
        migrations.AddField(
            model_name='service',
            name='service_type',
            field=models.CharField(choices=[('transport', 'نقل'), ('tour', 'جولة سياحية'), ('activity', 'نشاط ترفيهي'), ('meal', 'وجبات'), ('visa', 'تأشيرة'), ('insurance', 'تأمين سفر'), ('flight', 'طيران'), ('other', 'أخرى')], default='other', max_length=20, verbose_name='نوع الخدمة'),
        ),
        migrations.AddField(
            model_name='service',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='service',
            name='vehicle_capacity',
            field=models.PositiveIntegerField(default=1, verbose_name='سعة المركبة'),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='icon',
            field=models.CharField(blank=True, help_text='اسم أيقونة lucide-react مثل: car, plane, ship', max_length=50, verbose_name='أيقونة'),
        ),
        migrations.AlterField(
            model_name='service',
            name='max_participants',
            field=models.PositiveIntegerField(default=1, verbose_name='أقصى عدد مشاركين'),
        ),
        migrations.AlterField(
            model_name='service',
            name='vehicle_type',
            field=models.CharField(blank=True, max_length=100, verbose_name='نوع المركبة'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['city', 'service_type', 'is_active'], name='services_se_city_id_1242e4_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['base_price', 'currency'], name='services_se_base_pr_44cb3e_idx'),
        ),
    ]
