# Generated by Django 6.0.3 on 2026-04-11 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('hotels', '0003_hotel_amenities_hotel_check_in_time_and_more'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان الباقة')),
                ('description', models.TextField(blank=True, verbose_name='وصف الباقة')),
                ('image', models.ImageField(blank=True, null=True, upload_to='packages/', verbose_name='صورة الباقة')),
                ('total_nights', models.PositiveIntegerField(default=1, verbose_name='إجمالي الليالي')),
                ('total_days', models.PositiveIntegerField(default=2, verbose_name='إجمالي الأيام')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('published', 'منشورة'), ('archived', 'مؤرشفة')], default='draft', max_length=10, verbose_name='الحالة')),
                ('peak_surcharge_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='نسبة زيادة موسم الذروة %')),
                ('currency_cost', models.CharField(default='MYR', max_length=3, verbose_name='عملة التكلفة')),
                ('currency_sell', models.CharField(default='EUR', max_length=3, verbose_name='عملة البيع')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_packages', to='accounts.agency', verbose_name='الوكالة')),
            ],
            options={
                'verbose_name': 'باقة مخصصة',
                'verbose_name_plural': 'الباقات المخصصة',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PackageCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nights', models.PositiveIntegerField(default=1, verbose_name='عدد الليالي في المدينة')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتيب المدينة')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.city', verbose_name='المدينة')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='packages.custompackage', verbose_name='الباقة')),
            ],
            options={
                'verbose_name': 'مدينة في الباقة',
                'verbose_name_plural': 'مدن الباقة',
                'ordering': ['order'],
                'unique_together': {('package', 'city')},
            },
        ),
        migrations.CreateModel(
            name='PackageFlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_flight_code', models.CharField(blank=True, max_length=100, verbose_name='كود الرحلة')),
                ('price_adult_myr', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='سعر البالغ (MYR)')),
                ('price_child_myr', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='سعر الطفل (MYR)')),
                ('price_infant_myr', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='سعر الرضيع (MYR)')),
                ('from_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flights_from', to='locations.city', verbose_name='من مدينة')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flights', to='packages.custompackage', verbose_name='الباقة')),
                ('to_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flights_to', to='locations.city', verbose_name='إلى مدينة')),
            ],
            options={
                'verbose_name': 'رحلة طيران',
                'verbose_name_plural': 'رحلات الطيران',
            },
        ),
        migrations.CreateModel(
            name='PackageHotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(blank=True, max_length=100, verbose_name='نوع الغرفة')),
                ('rooms_count', models.PositiveIntegerField(default=1, verbose_name='عدد الغرف')),
                ('check_in_date', models.DateField(verbose_name='تاريخ الوصول')),
                ('check_out_date', models.DateField(verbose_name='تاريخ المغادرة')),
                ('nights', models.PositiveIntegerField(default=1, verbose_name='عدد الليالي')),
                ('price_per_room_night_myr', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='سعر الغرفة/ليلة (MYR)')),
                ('source', models.CharField(choices=[('manual', 'يدوي'), ('api', 'API خارجي')], default='manual', max_length=10, verbose_name='مصدر السعر')),
                ('api_reference_code', models.CharField(blank=True, max_length=100, verbose_name='كود الفندق في API')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotels.hotel', verbose_name='الفندق')),
                ('package_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotels', to='packages.packagecity', verbose_name='المدينة في الباقة')),
            ],
            options={
                'verbose_name': 'فندق في الباقة',
                'verbose_name_plural': 'فنادق الباقة',
            },
        ),
        migrations.CreateModel(
            name='PackagePaxConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adults_count', models.PositiveIntegerField(default=1, verbose_name='عدد البالغين')),
                ('children_count', models.PositiveIntegerField(default=0, verbose_name='عدد الأطفال (3-11)')),
                ('infants_count', models.PositiveIntegerField(default=0, verbose_name='عدد الرضع (0-2)')),
                ('extra_bed_children', models.BooleanField(default=False, verbose_name='سرير إضافي للأطفال')),
                ('extra_bed_infants', models.BooleanField(default=False, verbose_name='سرير إضافي للرضع')),
                ('package', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pax_config', to='packages.custompackage', verbose_name='الباقة')),
            ],
            options={
                'verbose_name': 'إعداد الأفراد',
                'verbose_name_plural': 'إعدادات الأفراد',
            },
        ),
        migrations.CreateModel(
            name='PackageProfitMargin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pax_from', models.PositiveIntegerField(verbose_name='من عدد أفراد')),
                ('pax_to', models.PositiveIntegerField(verbose_name='إلى عدد أفراد')),
                ('profit_per_adult_eur', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ربح البالغ (EUR)')),
                ('profit_per_child_eur', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ربح الطفل (EUR)')),
                ('profit_per_infant_eur', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ربح الرضيع (EUR)')),
                ('b2b_discount_eur', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='خصم B2B (EUR)')),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profit_margins', to='packages.custompackage', verbose_name='الباقة')),
            ],
            options={
                'verbose_name': 'هامش الربح',
                'verbose_name_plural': 'هوامش الربح',
                'ordering': ['pax_from'],
            },
        ),
        migrations.CreateModel(
            name='PackageTour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour_name', models.CharField(max_length=200, verbose_name='اسم الجولة')),
                ('price_adult_myr', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='سعر البالغ (MYR)')),
                ('price_child_myr', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='سعر الطفل (MYR)')),
                ('price_infant_myr', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='سعر الرضيع (MYR)')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.city', verbose_name='المدينة')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tours', to='packages.custompackage', verbose_name='الباقة')),
            ],
            options={
                'verbose_name': 'جولة سياحية',
                'verbose_name_plural': 'الجولات السياحية',
            },
        ),
        migrations.CreateModel(
            name='PackageTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_type', models.CharField(choices=[('airport_pickup', 'استقبال مطار'), ('intercity', 'نقل بين المدن'), ('local', 'نقل محلي')], max_length=20, verbose_name='نوع النقل')),
                ('price_myr', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='السعر (MYR)')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.city', verbose_name='المدينة')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='packages.custompackage', verbose_name='الباقة')),
            ],
            options={
                'verbose_name': 'نقل',
                'verbose_name_plural': 'خدمات النقل',
            },
        ),
        migrations.CreateModel(
            name='PackagePricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pax_count', models.PositiveIntegerField(verbose_name='عدد الأفراد')),
                ('total_cost_myr', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='إجمالي التكلفة (MYR)')),
                ('total_cost_eur', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='إجمالي التكلفة (EUR)')),
                ('selling_price_b2c_eur', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='سعر البيع B2C (EUR)')),
                ('selling_price_b2b_eur', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='سعر البيع B2B (EUR)')),
                ('price_per_pax_b2c_eur', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='سعر الفرد B2C (EUR)')),
                ('price_per_pax_b2b_eur', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='سعر الفرد B2B (EUR)')),
                ('calculated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ الحساب')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_table', to='packages.custompackage', verbose_name='الباقة')),
            ],
            options={
                'verbose_name': 'تسعير الباقة',
                'verbose_name_plural': 'جداول التسعير',
                'ordering': ['pax_count'],
                'unique_together': {('package', 'pax_count')},
            },
        ),
    ]
