# Generated by Django 6.0.3 on 2026-04-11 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='custompackage',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packages', to='locations.country', verbose_name='الدولة'),
        ),
    ]
