# Generated by Django 6.0.3 on 2026-04-12 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0002_custompackage_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='custompackage',
            name='client_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='إيميل العميل'),
        ),
        migrations.AddField(
            model_name='custompackage',
            name='client_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='اسم العميل'),
        ),
        migrations.AddField(
            model_name='custompackage',
            name='client_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='هاتف العميل'),
        ),
        migrations.AddField(
            model_name='custompackage',
            name='is_custom_order',
            field=models.BooleanField(default=False, verbose_name='باقة حسب الطلب'),
        ),
    ]
