# Generated by Django 6.0.3 on 2026-04-12 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0003_custompackage_client_email_custompackage_client_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='packageflight',
            name='profit_margin_pct',
            field=models.DecimalField(decimal_places=2, default=15, max_digits=5, verbose_name='هامش الربح %'),
        ),
        migrations.AddField(
            model_name='packagehotel',
            name='profit_margin_pct',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=5, verbose_name='هامش الربح %'),
        ),
        migrations.AddField(
            model_name='packagetour',
            name='profit_margin_pct',
            field=models.DecimalField(decimal_places=2, default=30, max_digits=5, verbose_name='هامش الربح %'),
        ),
        migrations.AddField(
            model_name='packagetransfer',
            name='profit_margin_pct',
            field=models.DecimalField(decimal_places=2, default=25, max_digits=5, verbose_name='هامش الربح %'),
        ),
    ]
