# Generated by Django 6.0.3 on 2026-04-09 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='You Need Travel', max_length=200, verbose_name='اسم الموقع')),
                ('site_logo', models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='شعار الموقع')),
                ('site_email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني')),
                ('site_phone', models.CharField(blank=True, max_length=20, verbose_name='الهاتف')),
                ('site_address', models.TextField(blank=True, verbose_name='العنوان')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'إعدادات الموقع',
                'verbose_name_plural': 'إعدادات الموقع',
            },
        ),
    ]
