# Generated by Django 6.0.3 on 2026-04-09 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الدولة')),
            ],
            options={
                'verbose_name': 'دولة',
                'verbose_name_plural': 'الدول',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم المدينة')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف المدينة')),
                ('image', models.ImageField(blank=True, null=True, upload_to='cities/', verbose_name='صورة المدينة')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='locations.country', verbose_name='الدولة')),
            ],
            options={
                'verbose_name': 'مدينة',
                'verbose_name_plural': 'المدن',
            },
        ),
    ]
