# Generated by Django 6.0.3 on 2026-04-09 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم المزود')),
                ('provider_type', models.CharField(choices=[('direct', 'عقد مباشر (Extranet)'), ('agoda', 'Agoda API'), ('booking', 'Booking.com API'), ('expedia', 'Expedia API'), ('custom', 'مزود مخصص')], default='direct', max_length=20, verbose_name='نوع المزود')),
                ('is_active', models.BooleanField(default=False, help_text='تفعيل أو تعطيل هذا المزود بضغطة زر دون التأثير على باقي النظام', verbose_name='مفعّل')),
                ('api_endpoint', models.URLField(blank=True, verbose_name='رابط API')),
                ('api_key', models.CharField(blank=True, max_length=500, verbose_name='مفتاح API')),
                ('api_secret', models.CharField(blank=True, max_length=500, verbose_name='Secret Key')),
                ('markup_percentage', models.DecimalField(decimal_places=2, default=0, help_text='نسبة الربح المضافة فوق سعر المزود', max_digits=5, verbose_name='Markup (%)')),
                ('priority', models.PositiveIntegerField(default=1, help_text='رقم أقل = أولوية أعلى في عرض النتائج', verbose_name='الأولوية')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'مزود بيانات',
                'verbose_name_plural': 'مزودو البيانات',
                'ordering': ['priority'],
            },
        ),
        migrations.CreateModel(
            name='HotelMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_hotel_id', models.CharField(max_length=200, verbose_name='معرّف الفندق عند المزود')),
                ('external_name', models.CharField(blank=True, help_text='الاسم كما يظهر في API المزود (قد يختلف عن اسمنا)', max_length=300, verbose_name='اسم الفندق عند المزود')),
                ('is_verified', models.BooleanField(default=False, help_text='هل تم التأكد يدوياً أن هذا نفس الفندق؟', verbose_name='تم التحقق')),
                ('last_synced', models.DateTimeField(blank=True, null=True, verbose_name='آخر مزامنة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_mappings', to='hotels.hotel', verbose_name='الفندق في النظام')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_mappings', to='providers.provider', verbose_name='المزود')),
            ],
            options={
                'verbose_name': 'ربط فندق بمزود',
                'verbose_name_plural': 'ربط الفنادق بالمزودين',
                'unique_together': {('hotel', 'provider')},
            },
        ),
        migrations.CreateModel(
            name='ProviderPriceCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField(verbose_name='تاريخ الوصول')),
                ('check_out', models.DateField(verbose_name='تاريخ المغادرة')),
                ('room_type', models.CharField(max_length=100, verbose_name='نوع الغرفة')),
                ('raw_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='السعر من المزود')),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='السعر بعد Markup')),
                ('currency', models.CharField(default='MYR', max_length=3)),
                ('cached_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(verbose_name='ينتهي الـ Cache')),
                ('is_available', models.BooleanField(default=True)),
                ('mapping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_cache', to='providers.hotelmapping', verbose_name='الربط')),
            ],
            options={
                'verbose_name': 'Cache سعر من مزود',
                'verbose_name_plural': 'Cache أسعار المزودين',
                'indexes': [models.Index(fields=['mapping', 'check_in', 'check_out'], name='providers_p_mapping_b38509_idx'), models.Index(fields=['expires_at'], name='providers_p_expires_064970_idx')],
            },
        ),
    ]
