# Generated by Django 6.0.3 on 2026-04-10 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnifiedSearchIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('hotel', 'فندق'), ('service', 'خدمة'), ('package', 'باقة')], max_length=10, verbose_name='نوع المحتوى')),
                ('object_id', models.PositiveIntegerField(verbose_name='معرف الكائن')),
                ('name', models.CharField(max_length=300, verbose_name='الاسم')),
                ('name_normalized', models.CharField(help_text='lowercase بدون مسافات زائدة للمقارنة', max_length=300, verbose_name='الاسم الموحد')),
                ('base_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='السعر الأساسي')),
                ('currency', models.CharField(default='MYR', max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('search_tags', models.JSONField(blank=True, default=list, help_text='["فندق","كوالا","5 نجوم","مسبح"]', verbose_name='كلمات بحث')),
                ('last_indexed', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.city', verbose_name='المدينة')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.country', verbose_name='الدولة')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='providers.provider', verbose_name='المزود')),
            ],
            options={
                'verbose_name': 'فهرس بحث موحد',
                'verbose_name_plural': 'فهارس البحث الموحدة',
                'indexes': [models.Index(fields=['content_type', 'is_active'], name='providers_u_content_b85ceb_idx'), models.Index(fields=['city', 'content_type'], name='providers_u_city_id_8b1266_idx'), models.Index(fields=['name_normalized'], name='providers_u_name_no_4b45ac_idx'), models.Index(fields=['base_price', 'currency'], name='providers_u_base_pr_eb0232_idx')],
                'unique_together': {('content_type', 'object_id')},
            },
        ),
    ]
