# Generated by Django 6.0.3 on 2026-04-11 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0002_unifiedsearchindex'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(choices=[('standard', 'Standard Room'), ('superior', 'Superior Room'), ('deluxe', 'Deluxe Room'), ('suite', 'Suite'), ('twin', 'Twin Room'), ('triple', 'Triple Room'), ('family', 'Family Room')], max_length=20, verbose_name='نوع الغرفة')),
                ('price_myr', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='سعر الشراكة (MYR/غرفة/ليلة)')),
                ('extra_bed_price_myr', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='سعر السرير الإضافي (MYR/ليلة)')),
                ('min_pax', models.PositiveIntegerField(default=1, verbose_name='الحد الأدنى للأفراد')),
                ('max_pax', models.PositiveIntegerField(default=8, verbose_name='الحد الأقصى للأفراد')),
                ('includes_breakfast', models.BooleanField(default=False, verbose_name='يشمل الفطور')),
                ('valid_from', models.DateField(verbose_name='صالح من')),
                ('valid_to', models.DateField(verbose_name='صالح حتى')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعّال')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات العقد')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mapping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_prices', to='providers.hotelmapping', verbose_name='ربط الفندق بالمزود')),
            ],
            options={
                'verbose_name': 'سعر عقد مباشر',
                'verbose_name_plural': 'أسعار العقود المباشرة',
                'ordering': ['mapping', 'room_type', 'min_pax'],
                'indexes': [models.Index(fields=['mapping', 'room_type'], name='providers_c_mapping_6fc4cc_idx'), models.Index(fields=['valid_from', 'valid_to'], name='providers_c_valid_f_7abc26_idx'), models.Index(fields=['is_active'], name='providers_c_is_acti_4748d6_idx')],
                'unique_together': {('mapping', 'room_type', 'min_pax', 'valid_from')},
            },
        ),
    ]
