# Generated by Django 6.0.3 on 2026-04-09 15:35

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('bookings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='الرصيد المتاح')),
                ('frozen_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='الرصيد المجمد (Escrow)')),
                ('currency', models.CharField(choices=[('MYR', 'Malaysian Ringgit'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('SAR', 'Saudi Riyal'), ('AED', 'UAE Dirham')], default='MYR', max_length=3, verbose_name='العملة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشطة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='accounts.agency', verbose_name='الوكالة')),
            ],
            options={
                'verbose_name': 'محفظة',
                'verbose_name_plural': 'المحافظ',
            },
        ),
        migrations.CreateModel(
            name='EscrowEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='المبلغ المجمد')),
                ('currency', models.CharField(default='MYR', max_length=3)),
                ('status', models.CharField(choices=[('frozen', 'مجمد'), ('released', 'محرر — خُصم نهائياً'), ('refunded', 'مُسترد')], default='frozen', max_length=10, verbose_name='الحالة')),
                ('frozen_at', models.DateTimeField(auto_now_add=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='escrow', to='bookings.booking', verbose_name='الحجز')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escrow_entries', to='wallet.wallet', verbose_name='المحفظة')),
            ],
            options={
                'verbose_name': 'قيد Escrow',
                'verbose_name_plural': 'قيود Escrow',
                'ordering': ['-frozen_at'],
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('credit', 'إيداع'), ('debit', 'سحب'), ('freeze', 'تجميد (Escrow)'), ('unfreeze', 'إلغاء تجميد'), ('refund', 'استرداد'), ('charge', 'خصم نهائي')], max_length=10, verbose_name='نوع العملية')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='المبلغ')),
                ('currency', models.CharField(default='MYR', max_length=3, verbose_name='العملة')),
                ('status', models.CharField(choices=[('pending', 'معلق'), ('completed', 'مكتمل'), ('failed', 'فاشل'), ('reversed', 'مُعكوس')], default='pending', max_length=10, verbose_name='الحالة')),
                ('balance_before', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='الرصيد قبل العملية')),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='الرصيد بعد العملية')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='مرجع العملية')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_transactions', to='bookings.booking', verbose_name='الحجز المرتبط')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_transactions', to=settings.AUTH_USER_MODEL, verbose_name='بواسطة')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='wallet.wallet', verbose_name='المحفظة')),
            ],
            options={
                'verbose_name': 'عملية محفظة',
                'verbose_name_plural': 'عمليات المحافظ',
                'ordering': ['-created_at'],
            },
        ),
    ]
