# Generated by Django 6.0.3 on 2026-04-09 15:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('hotels', '0001_initial'),
        ('locations', '0001_initial'),
        ('packages', '0001_initial'),
        ('pricing', '0001_initial'),
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_type', models.CharField(choices=[('agency', 'باقة الوكالة'), ('custom', 'باقة مخصصة')], default='custom', max_length=10, verbose_name='نوع الحجز')),
                ('status', models.CharField(choices=[('pending', 'معلق للمراجعة'), ('confirmed', 'مؤكد'), ('cancelled', 'ملغي'), ('completed', 'مكتمل')], default='pending', max_length=10, verbose_name='حالة الحجز')),
                ('client_name', models.CharField(max_length=200, verbose_name='اسم العميل')),
                ('client_phone', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('client_email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الالكتروني')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('adults', models.PositiveIntegerField(default=1, verbose_name='عدد البالغين')),
                ('children', models.PositiveIntegerField(default=0, verbose_name='عدد الاطفال')),
                ('infants', models.PositiveIntegerField(default=0, verbose_name='عدد الرضع')),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='السعر الاجمالي')),
                ('currency', models.CharField(default='MYR', max_length=3, verbose_name='العملة')),
                ('reference_number', models.CharField(blank=True, max_length=20, unique=True, verbose_name='رقم المرجع')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='accounts.agency', verbose_name='الوكالة')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.country', verbose_name='الدولة المقصودة')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='packages.tourpackage', verbose_name='الباقة السياحية')),
            ],
            options={
                'verbose_name': 'حجز',
                'verbose_name_plural': 'الحجوزات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookingCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nights', models.PositiveIntegerField(default=1, verbose_name='عدد الليالي')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='bookings.booking')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.city', verbose_name='المدينة')),
            ],
            options={
                'verbose_name': 'مدينة في الحجز',
                'verbose_name_plural': 'مدن الحجز',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='BookingHotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nights', models.PositiveIntegerField(default=1, verbose_name='عدد الليالي')),
                ('rooms_count', models.PositiveIntegerField(default=1, verbose_name='عدد الغرف')),
                ('price_per_night_snapshot', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='سعر الليلة وقت الحجز')),
                ('currency_snapshot', models.CharField(default='MYR', max_length=3, verbose_name='العملة وقت الحجز')),
                ('booking_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotels', to='bookings.bookingcity')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotels.hotel', verbose_name='الفندق')),
                ('room_price', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pricing.roomprice', verbose_name='تسعير الغرفة')),
            ],
            options={
                'verbose_name': 'فندق في الحجز',
                'verbose_name_plural': 'فنادق الحجز',
            },
        ),
        migrations.CreateModel(
            name='BookingPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_type', models.CharField(choices=[('adult', 'بالغ'), ('child', 'طفل'), ('infant', 'رضيع')], max_length=10)),
                ('age', models.PositiveIntegerField(blank=True, null=True, verbose_name='العمر')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='الاسم')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persons', to='bookings.booking')),
            ],
            options={
                'verbose_name': 'فرد في الحجز',
                'verbose_name_plural': 'افراد الحجز',
            },
        ),
        migrations.CreateModel(
            name='BookingService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='الكمية')),
                ('price_snapshot', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='السعر وقت الحجز')),
                ('currency_snapshot', models.CharField(default='MYR', max_length=3, verbose_name='العملة وقت الحجز')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='bookings.booking')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.service', verbose_name='الخدمة')),
            ],
            options={
                'verbose_name': 'خدمة في الحجز',
                'verbose_name_plural': 'خدمات الحجز',
            },
        ),
    ]
