# Generated by Django 6.0.3 on 2026-04-09 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نوع الغرفة')),
                ('max_occupancy', models.IntegerField(verbose_name='أقصى عدد نزلاء')),
                ('description', models.TextField(blank=True, verbose_name='وصف الغرفة')),
                ('image', models.ImageField(blank=True, null=True, upload_to='rooms/', verbose_name='صورة الغرفة')),
                ('breakfast_included', models.BooleanField(default=False, verbose_name='يشمل فطور الصباح')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_types', to='hotels.hotel', verbose_name='الفندق')),
            ],
            options={
                'verbose_name': 'نوع غرفة',
                'verbose_name_plural': 'أنواع الغرف',
            },
        ),
    ]
